---
- name: Install Postgresql server and client
  apt: pkg={{ item }}-{{ postgresql.version }} state=installed update-cache=yes
  register: postgresql_install
  with_items:
    - postgresql
  tags:
    - packages

- name: Install development header files
  apt: pkg={{ item }} state=installed update-cache=yes
  when: postgresql.install_development_headers == true
  with_items:
    - libpq-dev
  tags:
    - packages

- name: Install PostgreSQL config file
  template: src=postgresql.conf
            dest=/etc/postgresql/{{ postgresql.version }}/main/postgresql.conf
            owner={{ postgresql.user }} group={{ postgresql.group }}
  notify:
    - restart postgresql
  tags:
    - configuration
 
- name: Create postgres user for my app
    become: yes
    become_user: postgres
    postgresql_user:
      name: "myappuser"
      password: "supersecretpassword"

- name: Ensure we have access from the new user
    become: yes
    become_user: postgres
    postgresql_privs:
      db: mydatabase
      role: myappuser
      objs: ALL_IN_SCHEMA
      privs: SELECT,INSERT,UPDATE,DELETE
