name: Blob storage upload to web

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - uses: lauchacarro/Azure-Storage-Action@v1.0
      with:
        enabled-static-website: 'true'
        folder: 'tests'
        index-document: 'index.html'
        error-document: '404.html' 
        connection-string: ${{ secrets.AZURE_STORAGE }}
