name: Blob storage upload

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy react app to Azure blob storage'
      uses: bacongobbler/azure-blob-storage-upload@main
      with:
          source_dir: './*.*'
          connection_string: ${{ secrets.AZURE_STORAGE }} 
          sync: 'true'

   

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
